services:
  rabbitmq:
    image: 'rabbitmq:management'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=mysecret'
      - 'RABBITMQ_DEFAULT_USER=myuser'
    ports:
      - 5672:5672
      - 15672:15672
