server:
  port: 8080
spring:
  application:
    name: pocspringrabbitmqproducer
  rabbitmq:
    username: myuser
    password: mysecret
    host: localhost
  docker:
    compose:
      lifecycle-management: start-and-stop
      enabled: true
      file: src/main/resources/docker-compose.yml

poc.producer:
  exchange: "device-exchange"
  routingKeyPrefix: "device.outgoing."
  incomingQueuePrefix: "device.incoming."
